"""create interactions table

Revision ID: 2046f53820d4
Revises: 
Create Date: 2026-07-09 21:39:25.146000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2046f53820d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hcp_name', sa.String(length=255), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('topics_discussed', sa.JSON(), nullable=False),
    sa.Column('materials_shared', sa.JSON(), nullable=False),
    sa.Column('samples_distributed', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    # ### end Alembic commands ###
